import { StyleSheet } from "react-native";
import COLORS from "./colors";

export const contentHeaderStyles = StyleSheet.create({
  header: {
    backgroundColor: COLORS.backgroundSecondary,
    height: 70,
    flexDirection: "row",
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomColor: COLORS.primary,
    borderBottomWidth: 1,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    zIndex: 10,
  },
  leftPart: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  backButton: {
    padding: 4,
    backgroundColor: COLORS.surface,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  title: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 22,
    letterSpacing: 2,
    textShadowColor: COLORS.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  rightPart: {
    flexDirection: "row",
    alignItems: "center",
  },
  wallet: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 6,
    backgroundColor: COLORS.surface,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  walletInfo: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRightWidth: 1,
    borderColor: COLORS.primary,
    fontSize: 14,
  },
  walletAdd: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: COLORS.glowSoft,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
  },
});

export const homeHeaderStyles = StyleSheet.create({
  header: {
    backgroundColor: COLORS.backgroundSecondary,
    height: 70, 
    flexDirection: "row",
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomColor: COLORS.primary,
    borderBottomWidth: 1,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    zIndex: 10,
  },
  leftPart: {
    flex: 1,
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  logo: {
    width: 32,
    height: 32,
  },
  searchBox: {
    flex: 1,
    height: 36,
    backgroundColor: COLORS.surface,
    color: COLORS.primary,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
  },
  rightPart: {
    marginLeft: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  wallet: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 6,
    backgroundColor: COLORS.surface,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  walletInfo: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRightWidth: 1,
    borderColor: COLORS.primary,
    fontSize: 14,
  },
  walletAdd: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: COLORS.glowSoft,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
  },
});

export const floatBoxStyles = StyleSheet.create({
  box: {
    backgroundColor: COLORS.backgroundTertiary,
    width: "100%",
    height: "100%",
    borderColor: COLORS.glow,
    borderWidth: 1,
    borderRadius: 20,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    padding: 10,
    elevation: 10,
  },
});
