import { StyleSheet } from "react-native";

export const makeExploreStyles = (COLORS) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  bodyContent: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 16,
    marginVertical: 12,
    paddingHorizontal: 12,
    height: 42,
    backgroundColor: COLORS.inputBackground,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
    borderRadius: 6,
  },
  searchInput: {
    flex: 1,
    color: COLORS.text,
    fontFamily: "SpaceGrotesk",
    fontSize: 13,
  },

  // ===== Filter chip rows =====
  chipRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 16,
    marginTop: 10,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  chipActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.glowSoft,
  },
  chipText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 0.5,
  },
  chipTextActive: {
    color: COLORS.primary,
  },
  gameChip: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  gameChipActive: {
    borderColor: COLORS.secondary,
    backgroundColor: COLORS.glowSecondary,
  },
  gameChipText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 11,
    letterSpacing: 1,
  },
  gameChipTextActive: {
    color: COLORS.secondary,
  },

  // ===== Team rows (Teams view) =====
  teamRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.primary,
    borderRadius: 6,
    padding: 12,
    marginBottom: 8,
  },
  teamRowLogo: {
    width: 34,
    height: 34,
  },
  yearHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 18,
    marginBottom: 10,
  },
  yearText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
    letterSpacing: 2,
  },
  yearLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.border,
  },
  tournamentCard: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.accent,
    borderRadius: 6,
    padding: 12,
    marginBottom: 10,
  },
  tournamentHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  tournamentIcon: {
    width: 34,
    height: 34,
    borderRadius: 6,
    backgroundColor: COLORS.glowAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  rowInfo: {
    flex: 1,
  },
  rowTitle: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
  },
  rowSubtitle: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 11,
    marginTop: 2,
  },
  rowAction: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 10,
    letterSpacing: 1,
  },
  teamsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    paddingTop: 12,
  },
  teamChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  teamChipLogo: {
    width: 18,
    height: 18,
  },
  teamChipCode: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
  },
  noTeamsText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 11,
    marginTop: 10,
    fontStyle: "italic",
  },
});
