import { StyleSheet } from "react-native";

export const makeFriendsStyles = (COLORS) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundSecondary,
  },
  bodyContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  fixedTop: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  // ── My handle ──
  myHandleBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
  },
  myHandleLabel: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 11,
    letterSpacing: 1,
    marginBottom: 2,
  },
  myHandleText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
  },
  // ── Add friend ──
  addRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  addInput: {
    flex: 1,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: COLORS.text,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
  },
  addButton: {
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.glowSoft,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  addButtonText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1,
  },
  feedbackText: {
    fontFamily: "SpaceGrotesk",
    fontSize: 12,
    marginBottom: 12,
  },
  // ── Sections ──
  sectionLabel: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 2,
    marginTop: 8,
    marginBottom: 10,
  },
  emptyText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 13,
    marginBottom: 8,
  },
  // ── Rows ──
  personRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    gap: 12,
  },
  personAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.glowSoft,
    borderWidth: 1,
    borderColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  personAvatarText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
  },
  personName: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
  },
  personTag: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 12,
  },
  rowActions: {
    flexDirection: "row",
    gap: 8,
    marginLeft: "auto",
    alignItems: "center",
  },
  actionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
  },
  actionBtnText: {
    fontFamily: "SpaceGroteskBold",
    fontSize: 11,
    letterSpacing: 1,
  },
  // ── H2H scoreboard ──
  scoreboard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 20,
    marginBottom: 16,
  },
  scoreCol: {
    alignItems: "center",
    flex: 1,
  },
  scoreName: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 13,
    marginBottom: 4,
  },
  scoreValue: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 36,
  },
  scoreDivider: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 20,
  },
  scoreMeta: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 11,
    marginTop: 4,
  },
  wrappedButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: COLORS.glowSoft,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 14,
    marginBottom: 16,
  },
  wrappedButtonText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 13,
    letterSpacing: 1.5,
  },
  // ── Bet cards ──
  betCard: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.primary,
    borderRadius: 8,
    padding: 14,
    marginBottom: 10,
  },
  betHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  betName: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    flex: 1,
    marginRight: 8,
  },
  betTeamsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  betTeamText: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGrotesk",
    fontSize: 13,
  },
  betMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    paddingTop: 8,
    marginTop: 2,
  },
  betStake: {
    color: COLORS.warning,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
  },
  betResult: {
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1,
  },
});

export const makeFriendBetModalStyles = (COLORS) => StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "flex-end",
  },
  content: {
    backgroundColor: COLORS.backgroundSecondary,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 20,
    gap: 12,
  },
  title: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
    letterSpacing: 1.5,
  },
  fieldLabel: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 11,
    letterSpacing: 1,
    marginTop: 4,
  },
  chipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.glowSoft,
  },
  chipText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
  },
  chipTextActive: {
    color: COLORS.primary,
  },
  input: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: COLORS.text,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
  },
  errorText: {
    color: COLORS.danger,
    fontFamily: "SpaceGrotesk",
    fontSize: 12,
  },
  submitButton: {
    backgroundColor: COLORS.glowSoft,
    borderColor: COLORS.primary,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 4,
  },
  submitButtonText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 2,
  },
  cancelButton: {
    alignItems: "center",
    paddingVertical: 10,
  },
  cancelButtonText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1,
  },
  successBox: {
    alignItems: "center",
    gap: 10,
    paddingVertical: 20,
  },
  successText: {
    color: COLORS.success,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    textAlign: "center",
  },
  emptyFriendsText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 13,
  },
});

export const makeWrappedStyles = (COLORS) => StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  closeBtn: {
    position: "absolute",
    top: 54,
    right: 20,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
  },
  slide: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 36,
    gap: 18,
  },
  slideTitle: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 15,
    letterSpacing: 4,
    textAlign: "center",
  },
  slideHighlight: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 44,
    textAlign: "center",
    textShadowColor: COLORS.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 16,
  },
  slideText: {
    color: COLORS.text,
    fontFamily: "SpaceGrotesk",
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
  },
  dotsRow: {
    position: "absolute",
    bottom: 40,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.border,
  },
  dotActive: {
    backgroundColor: COLORS.primary,
    width: 20,
  },
  loadingBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  loadingText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
  },
});
