import { StyleSheet } from "react-native";

export const makeHelpStyles = (COLORS) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundSecondary,
  },
  chatList: {
    flex: 1,
  },
  chatContent: {
    padding: 16,
    gap: 12,
  },
  bubbleUser: {
    alignSelf: "flex-end",
    maxWidth: "85%",
    backgroundColor: COLORS.glowSoft,
    borderColor: COLORS.primary,
    borderWidth: 1,
    borderRadius: 12,
    borderBottomRightRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  bubbleAssistant: {
    alignSelf: "flex-start",
    maxWidth: "85%",
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 12,
    borderBottomLeftRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  bubbleText: {
    color: COLORS.text,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
    lineHeight: 20,
  },
  welcomeBox: {
    alignItems: "center",
    paddingVertical: 24,
    gap: 8,
  },
  welcomeTitle: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
    letterSpacing: 1,
  },
  welcomeHint: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 13,
    textAlign: "center",
    paddingHorizontal: 24,
  },
  suggestionWrap: {
    gap: 8,
    marginTop: 8,
    alignSelf: "stretch",
  },
  suggestionChip: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  suggestionText: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGrotesk",
    fontSize: 13,
  },
  ticketCta: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.glowSoft,
    borderColor: COLORS.primary,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  ticketCtaText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.background,
  },
  input: {
    flex: 1,
    minHeight: 44,
    maxHeight: 110,
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: COLORS.text,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: COLORS.glowSoft,
    borderColor: COLORS.primary,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  // ===== Ticket form modal =====
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.backgroundSecondary,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 20,
    gap: 12,
  },
  modalTitle: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
    letterSpacing: 1.5,
  },
  fieldLabel: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 11,
    letterSpacing: 1,
    marginTop: 4,
  },
  categoryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryChip: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  categoryChipActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.glowSoft,
  },
  categoryChipText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 11,
    letterSpacing: 1,
  },
  categoryChipTextActive: {
    color: COLORS.primary,
  },
  formInput: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: COLORS.text,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
  },
  formInputMultiline: {
    minHeight: 90,
    textAlignVertical: "top",
  },
  errorText: {
    color: COLORS.danger,
    fontFamily: "SpaceGrotesk",
    fontSize: 12,
  },
  submitButton: {
    backgroundColor: COLORS.glowSoft,
    borderColor: COLORS.primary,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 4,
  },
  submitButtonText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 2,
  },
  cancelButton: {
    alignItems: "center",
    paddingVertical: 10,
  },
  cancelButtonText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1,
  },
  successBox: {
    alignItems: "center",
    gap: 10,
    paddingVertical: 20,
  },
  successText: {
    color: COLORS.success,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    textAlign: "center",
  },
});
