import { StyleSheet } from "react-native";

export const makeHomeStyles = (COLORS) => StyleSheet.create({
  container: {
    backgroundColor: COLORS.background,
    flex: 1,
  },
  body: {
    flex: 1,
    paddingTop: 0,
  },
  bannerList: {
    flexDirection: "column",
    gap: 12,
    paddingHorizontal: 20,
    marginVertical: 12,
  },
  carouselContainer: {
    height: 220,
    marginBottom: 10,
  },
  carouselDotContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: -20,
    marginBottom: 10,
    zIndex: 10,
  },
  carouselDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.border,
    marginHorizontal: 4,
  },
  carouselDotActive: {
    backgroundColor: COLORS.primary,
    width: 24,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.8,
    shadowRadius: 5,
  },
  followedRow: {
    paddingHorizontal: 20,
    gap: 8,
    marginBottom: 4,
  },
  followedChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  followedLogo: {
    width: 20,
    height: 20,
  },
  followedCode: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 13,
  },
  promoTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
    gap: 10,
  },
  chooseSportTitle: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 0.5,
    paddingHorizontal: 20,
    marginTop: 15,
    marginBottom: 10,
  },
  esportsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: 15,
    gap: 12,
  },
  esportShortcut: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 12,
    gap: 8,
  },
  esportText: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
  },
  esportIcon: {
    fontSize: 18,
    color: COLORS.primary,
  },
  tabRow: {
    flexDirection: "row",
    paddingHorizontal: 20,
    marginVertical: 12,
    gap: 8,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
  },
  tabButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.glowSoft,
  },
  tabText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 0.5,
  },
  tabTextActive: {
    color: COLORS.primary,
  },
  featureCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 15,
  },
  featureHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  featureLeague: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
  },
  featureTime: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 12,
  },
  featureTeamsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  featureTeam: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  featureLogo: {
    width: 32,
    height: 32,
  },
  featureCode: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
  },
  featureVs: {
    color: COLORS.danger,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    marginHorizontal: 10,
  },
  featureBetButton: {
    backgroundColor: COLORS.glowSoft,
    borderColor: COLORS.primary,
    borderWidth: 1,
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: "center",
    marginTop: 10,
  },
  featureBetText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 1,
  },
  oddsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 12,
  },
  oddBoxCompact: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.backgroundTertiary,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  oddBoxLabel: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGrotesk",
    fontSize: 11,
  },
  oddBoxValue: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 13,
  },
  oddDetailBtn: {
    width: 38,
    height: 38,
    borderRadius: 6,
    backgroundColor: COLORS.backgroundTertiary,
    borderWidth: 1,
    borderColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  promoCard: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.danger,
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 20,
    marginVertical: 10,
    shadowColor: COLORS.danger,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
    position: "relative",
    overflow: "hidden",
  },
  promoBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: COLORS.badgeDangerBg,
    borderColor: COLORS.danger,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  promoBadgeText: {
    color: COLORS.badgeDangerText,
    fontFamily: "SpaceGroteskBold",
    fontSize: 10,
    letterSpacing: 1,
  },
  promoTitle: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 22,
    letterSpacing: 1,
    lineHeight: 28,
    marginBottom: 8,
    textShadowColor: COLORS.danger,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  promoSubtitle: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
    marginBottom: 20,
  },
  promoButton: {
    backgroundColor: COLORS.danger,
    borderRadius: 6,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  promoButtonText: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
    letterSpacing: 2,
  },
  promoQuoteBox: {
    backgroundColor: COLORS.backgroundTertiary,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
    padding: 12,
    borderRadius: 6,
    marginBottom: 16,
  },
  promoQuoteText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    lineHeight: 18,
    fontStyle: "italic",
  },
  promoResultRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 16,
  },
  promoResultCol: {
    flexDirection: "column",
    gap: 4,
  },
  promoResultLabel: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 10,
    letterSpacing: 0.5,
  },
  promoResultVal: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 13,
  },
  promoResultWin: {
    color: COLORS.success,
    fontFamily: "SpaceGroteskBold",
    fontSize: 13,
  },
  promoModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  promoModalContent: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: COLORS.backgroundSecondary,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: COLORS.danger,
    padding: 16,
    shadowColor: COLORS.danger,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 10,
  },
  promoModalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 12,
  },
  promoModalOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  promoModalOptionText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 13,
  },
  promoModalCloseBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  promoModalCloseText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 13,
  },
});

export const makeHomeBannerStyles = (COLORS) => StyleSheet.create({
  banner: {
    width: "100%",
    borderColor: COLORS.primary,
    borderWidth: 1.5,
    borderRadius: 6,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    marginVertical: 10,
    elevation: 8,
  },
  bannerImage: {
    width: "100%",
    height: 220,
  },
  bannerInfo: {
    backgroundColor: COLORS.overlayHeavy,
    borderRadius: 6,
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    gap: 15,
  },
  button: {
    backgroundColor: COLORS.backgroundTertiary,
    borderColor: COLORS.primary,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
    paddingHorizontal: 24,
    height: 48,
    borderRadius: 4,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.4,
    shadowRadius: 5,
  },
  buttonInfo: {
    color: COLORS.primary,
    fontSize: 16,
    fontFamily: "SpaceGroteskBold",
    letterSpacing: 1.5,
  },
  text: {
    color: COLORS.text,
    fontSize: 22,
    fontFamily: "SpaceGroteskBold",
    letterSpacing: 1,
    textShadowColor: COLORS.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
});
