import { StyleSheet } from "react-native";

export const makeScheduleStyles = (COLORS) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundSecondary,
  },
  body: {
    flex: 1,
  },
  bodyContent: {
    padding: 16,
    // Bottom clearance comes from TabBarSpacer in the list footer.
  },
  filterContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  filterTab: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  filterTabActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.glowSoft,
  },
  filterTabText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1,
  },
  filterTabTextActive: {
    color: COLORS.primary,
  },
  searchContainer: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: COLORS.backgroundSecondary,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchBar: {
    flex: 1,
    height: 40,
    backgroundColor: COLORS.surface,
    color: COLORS.primary,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
  },
  filtersButton: {
    height: 40,
    paddingHorizontal: 14,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  filtersButtonText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.backgroundSecondary,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 20,
    paddingBottom: 35,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingBottom: 10,
  },
  modalTitle: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 18,
    letterSpacing: 1,
  },
  modalCloseText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
  },
  filterSection: {
    marginBottom: 20,
  },
  filterSectionTitle: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1,
    marginBottom: 10,
  },
  filterChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filterChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  filterChipActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.glowSoft,
  },
  filterChipText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 11,
  },
  filterChipTextActive: {
    color: COLORS.primary,
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 10,
  },
  resetButton: {
    flex: 1,
    height: 48,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  applyButton: {
    flex: 2,
    height: 48,
    borderRadius: 6,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  resetButtonText: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
  },
  applyButtonText: {
    color: COLORS.background,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 1.5,
  },
  matchContainer: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderLeftColor: COLORS.primary,
    borderLeftWidth: 4,
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  matchHeader: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    paddingBottom: 8,
    marginBottom: 12,
    gap: 4,
  },
  leagueText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 1,
  },
  tournamentText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 12,
    letterSpacing: 0.5,
  },
  timeBadge: {
    alignSelf: "flex-start",
    backgroundColor: COLORS.badgeLiveBg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.glowSoft,
  },
  timeText: {
    color: COLORS.badgeLiveText,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
  },
  gameCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    marginBottom: 16,
  },
  teamCard: {
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  teamLogo: {
    width: 60,
    height: 60,
  },
  teamCode: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 18,
    letterSpacing: 1,
  },
  vsContainer: {
    padding: 8,
    backgroundColor: COLORS.backgroundTertiary,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.danger,
    shadowColor: COLORS.danger,
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  vsText: {
    color: COLORS.danger,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
  },
  detailButton: {
    backgroundColor: COLORS.backgroundTertiary,
    borderColor: COLORS.primary,
    borderWidth: 1,
    paddingVertical: 14,
    alignItems: "center",
    borderRadius: 6,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  detailButtonPressed: {
    backgroundColor: COLORS.glowSoft,
  },
  detailButtonText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 2,
  },
});

export const makeDetailStyles = (COLORS) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundSecondary,
  },
  centerBox: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: COLORS.danger,
    fontFamily: "SpaceGroteskBold",
    fontSize: 18,
  },
  bodyContent: {
    padding: 16,
    paddingBottom: 100, // Make room for fixed button
  },
  bottomFixedBox: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 34,
    backgroundColor: COLORS.backgroundSecondary,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  matchHeaderBox: {
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    padding: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 24,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  leagueText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 2,
  },
  leagueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 20,
  },
  followMatchBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginLeft: "auto",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.glowSoft,
  },
  followMatchBtnActive: {
    backgroundColor: COLORS.primary,
  },
  followMatchBtnText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 11,
    letterSpacing: 1,
  },
  followMatchBtnTextActive: {
    color: COLORS.buttonPrimaryText,
  },
  challengeBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.secondary,
    backgroundColor: COLORS.backgroundTertiary,
  },
  challengeBtnText: {
    color: COLORS.secondary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1.5,
  },
  teamHint: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 9,
    letterSpacing: 1,
    marginTop: 4,
  },
  standingsLink: {
    marginTop: 16,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.backgroundTertiary,
  },
  standingsLinkText: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 11,
    letterSpacing: 1,
  },
  teamsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  teamCol: {
    alignItems: "center",
    flex: 1,
  },
  logoLarge: {
    width: 80,
    height: 80,
    marginBottom: 10,
  },
  teamCode: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 20,
    letterSpacing: 1,
  },
  vsBox: {
    padding: 10,
    backgroundColor: COLORS.backgroundTertiary,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.secondary,
    shadowColor: COLORS.secondary,
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  vsText: {
    color: COLORS.secondary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
  },
  sectionTitle: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 2,
    marginBottom: 12,
  },
  marketRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 30,
  },
  marketGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  oddBox: {
    flex: 1,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 16,
    alignItems: "center",
  },
  oddBoxSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.glowSoft,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  oddBoxSecondary: {
    padding: 8,
    backgroundColor: COLORS.backgroundSecondary, // Darker inside the surface card
    borderWidth: 0,
  },
  secondaryMarketCard: {
    width: "48%",
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 8,
    marginBottom: 16,
  },
  secondaryMarketHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    gap: 4,
  },
  secondaryMarketTitle: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 11,
    textAlign: 'center',
  },
  oddTeamCode: {
    color: COLORS.text,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
    marginBottom: 8,
  },
  oddTeamCodeSecondary: {
    fontSize: 12,
    marginBottom: 4,
  },
  oddValue: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 22,
  },
  oddValueSecondary: {
    fontSize: 16,
  },
  betSlipBox: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    padding: 20,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  betSlipTitle: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
    letterSpacing: 2,
    marginBottom: 20,
    textAlign: "center",
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.backgroundTertiary,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  currencyPrefix: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 24,
    marginRight: 10,
  },
  wagerInput: {
    flex: 1,
    height: 60,
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 24,
  },
  payoutRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingTop: 16,
    borderTopWidth: 1,
    borderColor: COLORS.divider,
  },
  payoutLabel: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1,
  },
  payoutValue: {
    color: COLORS.success,
    fontFamily: "SpaceGroteskBold",
    fontSize: 20,
    textShadowColor: COLORS.success,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  submitButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: 6,
    alignItems: "center",
    shadowColor: COLORS.primary,
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: COLORS.background,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
    letterSpacing: 2,
  },
  // Added from BetHistorySection refactor
  betCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 16,
    marginBottom: 12,
  },
  betHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    paddingBottom: 8,
  },
  betMarketLabel: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
  },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: COLORS.glowSoft,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  statusPillText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 10,
  },
  betOutcomeLabel: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 12,
    marginBottom: 4,
  },
  betOutcomeValue: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
  },
  betMoneyLabel: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
  },
  summaryBox: {
    backgroundColor: COLORS.cardElevated,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 16,
    marginTop: 8,
    marginBottom: 20,
  },
  summaryTitle: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1,
    marginBottom: 12,
    textAlign: "center",
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    paddingBottom: 8,
  },
  summaryLabel: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
  },
  summaryValue: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
  },
});
