import { StyleSheet } from "react-native";
import COLORS from "./colors";

export const scheduleStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundSecondary,
  },
  body: {
    flex: 1,
  },
  bodyContent: {
    padding: 16,
    paddingBottom: 40,
  },
  matchContainer: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderLeftColor: COLORS.primary,
    borderLeftWidth: 4,
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  matchHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    paddingBottom: 8,
    marginBottom: 12,
  },
  leagueText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 1,
  },
  tournamentText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 12,
    letterSpacing: 0.5,
  },
  timeBadge: {
    alignSelf: "flex-start",
    backgroundColor: COLORS.badgeLiveBg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.glowSoft,
  },
  timeText: {
    color: COLORS.badgeLiveText,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
  },
  gameCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    marginBottom: 16,
  },
  teamCard: {
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  teamLogo: {
    width: 60,
    height: 60,
  },
  teamCode: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 18,
    letterSpacing: 1,
  },
  vsContainer: {
    padding: 8,
    backgroundColor: COLORS.backgroundTertiary,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.danger,
    shadowColor: COLORS.danger,
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  vsText: {
    color: COLORS.danger,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
  },
  detailButton: {
    backgroundColor: COLORS.backgroundTertiary,
    borderColor: COLORS.primary,
    borderWidth: 1,
    paddingVertical: 14,
    alignItems: "center",
    borderRadius: 6,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  detailButtonPressed: {
    backgroundColor: COLORS.glowSoft,
  },
  detailButtonText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 2,
  },
});

export const detailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundSecondary,
  },
  centerBox: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: COLORS.danger,
    fontFamily: "SpaceGroteskBold",
    fontSize: 18,
  },
  bodyContent: {
    padding: 16,
    paddingBottom: 40,
  },
  matchHeaderBox: {
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    padding: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 24,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  leagueText: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 2,
    marginBottom: 20,
  },
  teamsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  teamCol: {
    alignItems: "center",
    flex: 1,
  },
  logoLarge: {
    width: 80,
    height: 80,
    marginBottom: 10,
  },
  teamCode: {
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 20,
    letterSpacing: 1,
  },
  vsBox: {
    padding: 10,
    backgroundColor: COLORS.backgroundTertiary,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.danger,
    shadowColor: COLORS.danger,
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  vsText: {
    color: COLORS.danger,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
  },
  sectionTitle: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 2,
    marginBottom: 12,
  },
  marketRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 30,
  },
  oddBox: {
    flex: 1,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 16,
    alignItems: "center",
  },
  oddBoxSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.glowSoft,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  oddTeamCode: {
    color: COLORS.text,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
    marginBottom: 8,
  },
  oddValue: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 22,
  },
  betSlipBox: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    padding: 20,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  betSlipTitle: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
    letterSpacing: 2,
    marginBottom: 20,
    textAlign: "center",
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.backgroundTertiary,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  currencyPrefix: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 24,
    marginRight: 10,
  },
  wagerInput: {
    flex: 1,
    height: 60,
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 24,
  },
  payoutRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingTop: 16,
    borderTopWidth: 1,
    borderColor: COLORS.divider,
  },
  payoutLabel: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
    letterSpacing: 1,
  },
  payoutValue: {
    color: COLORS.success,
    fontFamily: "SpaceGroteskBold",
    fontSize: 20,
    textShadowColor: COLORS.success,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  submitButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: 6,
    alignItems: "center",
    shadowColor: COLORS.primary,
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: COLORS.background,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
    letterSpacing: 2,
  },
});
