import { StyleSheet } from "react-native";

export const makeProfileStyles = (COLORS) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  body:{
    paddingHorizontal: 20,
  },
  bodyContent: {
    paddingVertical: 10,
    marginTop: 20,
    minHeight: 110,
    height: 'auto',
  },
  profileInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 5,
  },
  vipBadge: {
    alignSelf: "flex-start",
    backgroundColor: COLORS.vipGoldBg,
    borderColor: COLORS.vipGold,
    borderWidth: 1,
    borderRadius: 15,
    paddingHorizontal: 8,
    paddingVertical: 3,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  vipText: {
    color: COLORS.vipGoldDark,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
  },
  activityList: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  activityItem: {
    width: "31%",
    marginBottom: 15,
  },
  floatBoxWrapper: {
    height: 110,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 15,
  },
  itemContent: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  text: {
    color: COLORS.text,
    fontSize: 18,
    fontFamily: "Manrope",
    paddingVertical: 3,
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 20,
    paddingHorizontal: 2,
  },
  sectionCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  sectionTitle: {
    color: COLORS.textSecondary,
    fontSize: 13,
    fontFamily: "ManropeBold",
    marginBottom: 8,
    marginLeft: 6,
    textTransform: "uppercase",
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  settingLabelWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  settingText: {
    color: COLORS.text,
    fontSize: 14,
    fontFamily: "ManropeBold",
    marginLeft: 10,
  },
  settingHint: {
    color: COLORS.textMuted,
    fontSize: 13,
  },
  logoutButton: {
    backgroundColor: COLORS.buttonDanger,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    borderRadius: 12,
    marginTop: 15,
    marginBottom: 40,
    elevation: 3,
    shadowColor: COLORS.buttonDanger,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  logoutText: {
    color: COLORS.buttonDangerText,
    fontSize: 16,
    fontFamily: "ManropeBold",
  },
  vipPill: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  vipPillText: {
    color: COLORS.buttonDangerText,
    fontSize: 13,
    fontFamily: "ManropeBold",
    marginLeft: 5,
  },
  vipUpsell: {
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    elevation: 5,
  },
  vipUpsellText: {
    color: COLORS.buttonDangerText,
    fontSize: 18,
    fontFamily: "ManropeBold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
});

