import { StyleSheet } from "react-native";
import COLORS from "./colors";

export const walletStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundSecondary,
  },
  body: {
    flex: 1,
  },
  bodyContent: {
    padding: 20,
  },
  balanceCard: {
    backgroundColor: COLORS.cardElevated,
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
    marginBottom: 30,
  },
  balanceCardWithdraw: {
    backgroundColor: COLORS.cardElevated,
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.danger,
    shadowColor: COLORS.danger,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
    marginBottom: 30,
  },
  walletIconBox: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.glowSoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  walletIconBoxWithdraw: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255, 77, 103, 0.15)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  balanceLabel: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 2,
    marginBottom: 8,
  },
  balanceAmount: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 32,
    textShadowColor: COLORS.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  balanceAmountWithdraw: {
    color: COLORS.danger,
    fontFamily: "SpaceGroteskBold",
    fontSize: 32,
    textShadowColor: COLORS.danger,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    color: COLORS.textSecondary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    marginBottom: 10,
    letterSpacing: 1,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 60,
  },
  inputPrefix: {
    color: COLORS.primary,
    fontFamily: "SpaceGroteskBold",
    fontSize: 20,
    marginRight: 10,
  },
  inputPrefixWithdraw: {
    color: COLORS.danger,
    fontFamily: "SpaceGroteskBold",
    fontSize: 20,
    marginRight: 10,
  },
  amountInput: {
    flex: 1,
    color: COLORS.text,
    fontFamily: "SpaceGroteskBold",
    fontSize: 20,
  },
  inputSuffix: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
  },
  bottomFixedBox: {
    padding: 20,
    backgroundColor: COLORS.backgroundSecondary,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  payButton: {
    backgroundColor: COLORS.primary,
    height: 56,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  withdrawButton: {
    backgroundColor: COLORS.danger,
    height: 56,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  payButtonDisabled: {
    opacity: 0.5,
  },
  payButtonText: {
    color: COLORS.background,
    fontFamily: "SpaceGroteskBold",
    fontSize: 16,
    letterSpacing: 1,
  },
  sectionTitle: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGroteskBold",
    fontSize: 14,
    letterSpacing: 2,
    marginBottom: 16,
    marginTop: 10,
  },
  emptyHistoryText: {
    color: COLORS.textMuted,
    fontFamily: "SpaceGrotesk",
    fontSize: 14,
    textAlign: "center",
    marginTop: 20,
  },
  infoBox: {
    flexDirection: "row",
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(59, 130, 246, 0.3)",
    gap: 12,
    marginBottom: 20,
  },
  infoText: {
    flex: 1,
    color: COLORS.textSecondary,
    fontFamily: "SpaceGrotesk",
    fontSize: 13,
    lineHeight: 20,
  },
  withdrawAllBtn: {
    position: "absolute",
    right: 16,
    backgroundColor: COLORS.badgeDangerBg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.danger,
  },
  withdrawAllText: {
    color: COLORS.danger,
    fontFamily: "SpaceGroteskBold",
    fontSize: 12,
  },
});
