import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { pool } from '../src/config/db.config.js';
import dotenv from 'dotenv';
dotenv.config();

// Exports the CURRENT database content into seeds/seed.sql so the whole
// sample dataset can be re-imported later with a single `npm run seed`.
// Dumped tables are content/sample data only — user accounts, wallets and
// bets are intentionally excluded.
//   node scripts/generate-seed.js

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_FILE = path.join(__dirname, '..', 'seeds', 'seed.sql');

// FK-safe insert order.
const TABLES = [
  'leagues',
  'teams',
  'tournaments',
  'matchtypes',
  'matches',
  'games',
  'players',
  'gameplayerstats',
  'gameevents',
  'betmarkets',
  'odds',
  'viptiers',
  'promotions',
];

const sqlValue = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number' || typeof v === 'bigint') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (v instanceof Date) return `'${v.toISOString()}'`;
  // json/jsonb columns come back as parsed objects/arrays from pg.
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const run = async () => {
  const lines = [];
  lines.push('-- =====================================================================');
  lines.push('-- SEED DATA — generated by scripts/generate-seed.js');
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push('-- Import with:  npm run seed   (or: node run-seed.js)');
  lines.push('-- NOTE: truncates and re-fills the content tables below.');
  lines.push('--       Users / wallets / bets are NOT touched by this seed,');
  lines.push('--       but bets referencing old markets are removed via CASCADE.');
  lines.push('-- =====================================================================');
  lines.push('');
  lines.push('BEGIN;');
  lines.push('');
  lines.push(`TRUNCATE ${TABLES.join(', ')} RESTART IDENTITY CASCADE;`);
  lines.push('');

  for (const table of TABLES) {
    // Only global promotions belong in the seed; user-assigned ones are runtime data.
    const where = table === 'promotions' ? 'WHERE user_id IS NULL' : '';
    const { rows, fields } = await pool.query(`SELECT * FROM ${table} ${where} ORDER BY id`);
    lines.push(`-- ===== ${table} (${rows.length} rows) =====`);
    if (rows.length === 0) {
      lines.push('');
      continue;
    }
    const cols = fields.map(f => f.name);
    for (const row of rows) {
      const values = cols.map(c => sqlValue(row[c])).join(', ');
      lines.push(
        `INSERT INTO ${table} (${cols.join(', ')}) OVERRIDING SYSTEM VALUE VALUES (${values});`
      );
    }
    // Keep the identity sequence in sync with explicit ids.
    lines.push(
      `SELECT setval(pg_get_serial_sequence('${table}', 'id'), (SELECT COALESCE(MAX(id), 1) FROM ${table}));`
    );
    lines.push('');
  }

  lines.push('COMMIT;');
  lines.push('');

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
  console.log(`Seed written to ${OUT_FILE}`);
  process.exit(0);
};

run().catch((err) => {
  console.error('Seed generation failed:', err);
  process.exit(1);
});
